name: Deploy to Google Cloud Run

on:
  push:
    tags:
      - "release*"

env:
  PROJECT_ID: dobli-404219
  GAR_LOCATION: us-central1
  APP: dobli
  GCP_STORAGE_BUCKET_NAME: dobli-audio-snippets
  REGION: us-central1 # specify the region for Cloud Run

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Docker auth
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push container
        run: |
          docker build \
          --build-arg YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --build-arg GCP_SA=${{ secrets.GCP_SA }} \
          --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --build-arg AUDIO_SNIPPET_BUCKET=${{ secrets.AUDIO_SNIPPET_BUCKET }} \
          --build-arg GOOGLE_PROJECT_ID=${{ env.PROJECT_ID }} \
          -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" \
          -f ./Dockerfile .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP }} \
            --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated # Optionally allow unauthenticated access to your service. Remove this flag if you want authenticated access only.
